all:
  children:
    database:
      hosts:
        aap-database:
          ansible_host: 192.168.100.12
    controller:
      hosts:
        aap-controller:
          ansible_host: 192.168.100.10
    hub:
      hosts:
        aap-hub:
          ansible_host: 192.168.100.11
    aap:
      children:
        database:
        controller:
        hub:
  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'